import React from 'react';
import "lotti/styles/globals.css";
import {Inter} from "next/font/google";
import {cookies} from "next/headers";
import {TRPCReactProvider} from "lotti/trpc/react";
import Sidebar from "lotti/components/Sidebar";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{rel: "icon", url: "/favicon.ico"}],
};

export default function RootLayout({children,}:
{
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-full">
    <body className={`font-sans ${inter.variable} h-full`}>
    <TRPCReactProvider cookies={cookies().toString()}>
      <div className="flex h-full">
        <Sidebar/>
        <main className="flex-1 h-full">
          {children}
        </main>
      </div>
    </TRPCReactProvider>
    </body>
    </html>
  );
}
